{% set name = "redmail" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/redmail-{{ version }}.tar.gz
  sha256: 97567afeaa8a2f3343d8648810437a86b70a6894e49df482a4eb2b751fd56084

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - versioneer
  run:
    - jinja2
    - python >=3.6

test:
  source_files:
    - redmail/test
  imports:
    - redmail
    - redmail.email
    - redmail.models
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys -k "not send_function" redmail/test
  requires:
    - pip
    - pytest

about:
  home: https://github.com/Miksus/red-mail
  doc_url: https://red-mail.readthedocs.io/en/latest/
  summary: Email sending library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
