{% set name = "redmail" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/redmail-{{ version }}.tar.gz
  sha256: 0447cbd76deb2788b2d831c12e22b513587e99f725071d9951a01b0f2b8d0a72

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=45
    - setuptools_scm >=6.2
  run:
    - jinja2
    - python >={{ python_min }}

test:
  source_files:
    - redmail/test
  imports:
    - redmail
    - redmail.email
    - redmail.models
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys -k "not send_function" redmail/test
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/Miksus/red-mail
  doc_url: https://red-mail.readthedocs.io/en/latest/
  summary: Email sending library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
