{% set name = "redmail" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/redmail-{{ version }}.tar.gz
  sha256: 29f362a89ff03a561c2f7fccfc9cf583c0b8d53f2cb126b2a7d42092e72dc070

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=45
    - setuptools_scm >=6.2
  run:
    - jinja2
    - python >=3.6

test:
  source_files:
    - redmail/test
  imports:
    - redmail
    - redmail.email
    - redmail.models
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys -k "not send_function" redmail/test
  requires:
    - pip
    - pytest

about:
  home: https://github.com/Miksus/red-mail
  doc_url: https://red-mail.readthedocs.io/en/latest/
  summary: Email sending library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
